version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo "trying to build the app now"
      - ls
      - npm run build
      - ls
      - echo "The process has finished"

artifacts:
  files:
    - 'build/*'
  name: my-webapp-artifacts
