version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo "trying to build the app now"
      - ls
      - npm run build
      - ls
      - echo "The process has finished"
      - aws s3 sync build s3://dominic-react-test-app
