version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  build:
    commands:
      - echo "trying to build the app now"
      - yarn build
      - echo "The process has finished"

artifacts:
  files:
    - '**/*'
  name: my-webapp-artifacts
